test_that("igraph_style() works", {
  expect_snapshot(styler::style_text("A -- B -- C -- D", style = igraph_style))
  expect_snapshot(styler::style_text("A - +B:C", style = igraph_style))
  expect_snapshot(styler::style_text("A+-+B", style = igraph_style))
  expect_snapshot(styler::style_text("A+--+B", style = igraph_style))
  expect_snapshot(styler::style_text("A+---+B", style = igraph_style))
  expect_snapshot(styler::style_text("A+-B", style = igraph_style))
  expect_snapshot(styler::style_text("A+--B", style = igraph_style))
  expect_snapshot(styler::style_text("A+---B", style = igraph_style))
  expect_snapshot(styler::style_text("A-+B", style = igraph_style))
  expect_snapshot(styler::style_text("A--+B", style = igraph_style))
  expect_snapshot(styler::style_text("A---+B", style = igraph_style))
  expect_snapshot(styler::style_text("A----+B", style = igraph_style))
})
